---
abstract: 'render SVG into a Cairo surface'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-CairoSVG
no_index:
  directory:
    - t
    - inc
requires:
  Cairo: 0
  Image::SVG::Path: 0.18
  XML::Parser: 0
  perl: 5.006001
resources:
  bugtracker: https://github.com/benkasminbullock/image-cairosvg/issues
  repository: git://github.com/benkasminbullock/image-cairosvg.git
version: 0.01
